export const SHOW_TO_ENCRYPT_PAGE = 'SHOW_TO_ENCRYPT_PAGE';
export const SHOW_TO_DECRYPT_PAGE = 'SHOW_TO_DECRYPT_PAGE';
export const ENCRYPT_MESSAGE = 'ENCRYPT_MESSAGE';
export const DECRYPT_MESSAGE = 'DECRYPT_MESSAGE';